dist: trusty
sudo: false
notifications:
  email: false
env:
  - RELEASE_TAG="release-$TRAVIS_BUILD_NUMBER"
if: tag IS blank

jobs:
  include:
    - stage: build and publish
      language: java
      jdk: oraclejdk8
      script: ./gradlew clean build
      deploy:
        provider: heroku
        file: "build/libs/resource-allocator-0.0.1-SNAPSHOT.jar"
        skip_cleanup: true
        api_key:
          secure: $HEROKU_API_KEY