dist: trusty
sudo: false
notifications:
  email: false
env:
  - RELEASE_TAG="release-$TRAVIS_BUILD_NUMBER"
if: tag IS blank

jobs:
  include:
    - stage: build and publish
      language: java
      jdk: oraclejdk8
      script: ./gradlew clean build
      before_deploy:
        - git config --local user.name "Travis CI"
        - git config --local user.email "travis@example.com"
        - git tag -f $RELEASE_TAG
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        file: "build/libs/resource-allocator-0.0.1-SNAPSHOT.jar"
        skip_cleanup: true
    - stage: deploy to azure
      script:
        - echo "Downloading $RELEASE_TAG"
        - wget -P build/libs https://github.com/$GITHUB_USERNAME/ResourceAllocator/releases/download/$RELEASE_TAG/resource-allocator-0.0.1-SNAPSHOT.jar
      deploy:
        skip_cleanup: true
        on: master
        provider: azure_web_apps